// Bảng số lượng tối đa cho phép đặt của từng loại công trình theo cấp Town Hall (TH1 -> TH18)
export const TH_BUILDING_LIMITS: Record<number, Record<string, number>> = {
  1: {
    "town-hall": 1,
    "cannon": 1,
    "gold-mine": 1,
    "elixir-collector": 1,
    "gold-storage": 1,
    "elixir-storage": 1,
    "army-camp": 1,
    "barracks": 1,
    "wall": 0,
  },
  2: {
    "town-hall": 1,
    "cannon": 2,
    "archer-tower": 1,
    "gold-mine": 2,
    "elixir-collector": 2,
    "gold-storage": 1,
    "elixir-storage": 1,
    "army-camp": 1,
    "barracks": 1,
    "clan-castle": 1,
    "wall": 25,
  },
  3: {
    "town-hall": 1,
    "cannon": 2,
    "archer-tower": 1,
    "mortar": 1,
    "gold-mine": 3,
    "elixir-collector": 3,
    "gold-storage": 2,
    "elixir-storage": 2,
    "army-camp": 2,
    "barracks": 1,
    "laboratory": 1,
    "clan-castle": 1,
    "bomb": 2,
    "wall": 50,
  },
  4: {
    "town-hall": 1,
    "cannon": 2,
    "archer-tower": 2,
    "mortar": 1,
    "air-defense": 1,
    "gold-mine": 4,
    "elixir-collector": 4,
    "gold-storage": 2,
    "elixir-storage": 2,
    "army-camp": 2,
    "barracks": 1,
    "laboratory": 1,
    "clan-castle": 1,
    "bomb": 2,
    "spring-trap": 2,
    "wall": 75,
  },
  5: {
    "town-hall": 1,
    "cannon": 3,
    "archer-tower": 3,
    "mortar": 1,
    "air-defense": 1,
    "wizard-tower": 1,
    "gold-mine": 5,
    "elixir-collector": 5,
    "gold-storage": 2,
    "elixir-storage": 2,
    "army-camp": 3,
    "barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "clan-castle": 1,
    "bomb": 4,
    "spring-trap": 2,
    "air-bomb": 2,
    "wall": 100,
  },
  6: {
    "town-hall": 1,
    "cannon": 3,
    "archer-tower": 3,
    "mortar": 2,
    "air-defense": 2,
    "wizard-tower": 2,
    "air-sweeper": 1,
    "gold-mine": 6,
    "elixir-collector": 6,
    "gold-storage": 2,
    "elixir-storage": 2,
    "army-camp": 3,
    "barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "clan-castle": 1,
    "bomb": 4,
    "spring-trap": 2,
    "air-bomb": 2,
    "giant-bomb": 1,
    "wall": 125,
  },
  7: {
    "town-hall": 1,
    "cannon": 5,
    "archer-tower": 4,
    "mortar": 3,
    "air-defense": 3,
    "wizard-tower": 2,
    "air-sweeper": 1,
    "hidden-tesla": 2,
    "barbarian-king": 1,
    "gold-mine": 6,
    "elixir-collector": 6,
    "dark-elixir-drill": 1,
    "gold-storage": 2,
    "elixir-storage": 2,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "clan-castle": 1,
    "bomb": 6,
    "spring-trap": 4,
    "air-bomb": 2,
    "giant-bomb": 2,
    "seeking-air-mine": 1,
    "wall": 175,
  },
  8: {
    "town-hall": 1,
    "cannon": 5,
    "archer-tower": 5,
    "mortar": 4,
    "air-defense": 3,
    "wizard-tower": 3,
    "air-sweeper": 1,
    "hidden-tesla": 3,
    "bomb-tower": 1,
    "barbarian-king": 1,
    "archer-queen": 1,
    "gold-mine": 6,
    "elixir-collector": 6,
    "dark-elixir-drill": 2,
    "gold-storage": 3,
    "elixir-storage": 3,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "clan-castle": 1,
    "bomb": 6,
    "spring-trap": 6,
    "air-bomb": 4,
    "giant-bomb": 3,
    "seeking-air-mine": 2,
    "skeleton-trap": 2,
    "wall": 225,
  },
  9: {
    "town-hall": 1,
    "cannon": 5,
    "archer-tower": 6,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 4,
    "air-sweeper": 2,
    "hidden-tesla": 4,
    "bomb-tower": 1,
    "xbow": 2,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "gold-mine": 6,
    "elixir-collector": 6,
    "dark-elixir-drill": 2,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "clan-castle": 1,
    "bomb": 6,
    "spring-trap": 6,
    "air-bomb": 4,
    "giant-bomb": 4,
    "seeking-air-mine": 4,
    "skeleton-trap": 2,
    "wall": 250,
  },
  10: {
    "town-hall": 1,
    "cannon": 6,
    "archer-tower": 7,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 4,
    "air-sweeper": 2,
    "hidden-tesla": 4,
    "bomb-tower": 2,
    "xbow": 3,
    "inferno-tower": 2,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "clan-castle": 1,
    "bomb": 6,
    "spring-trap": 6,
    "air-bomb": 5,
    "giant-bomb": 5,
    "seeking-air-mine": 5,
    "skeleton-trap": 3,
    "wall": 275,
  },
  11: {
    "town-hall": 1,
    "cannon": 7,
    "archer-tower": 8,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 4,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 2,
    "eagle-artillery": 1,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "clan-castle": 1,
    "bomb": 6,
    "spring-trap": 6,
    "air-bomb": 5,
    "giant-bomb": 5,
    "seeking-air-mine": 5,
    "skeleton-trap": 3,
    "tornado-trap": 1,
    "wall": 300,
  },
  12: {
    "town-hall": 1,
    "cannon": 7,
    "archer-tower": 8,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 5,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 3,
    "eagle-artillery": 1,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "workshop": 1,
    "clan-castle": 1,
    "bomb": 6,
    "spring-trap": 8,
    "air-bomb": 6,
    "giant-bomb": 6,
    "seeking-air-mine": 6,
    "skeleton-trap": 3,
    "tornado-trap": 1,
    "wall": 300,
  },
  13: {
    "town-hall": 1,
    "cannon": 7,
    "archer-tower": 8,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 5,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 3,
    "eagle-artillery": 1,
    "scattershot": 2,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "royal-champion": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "workshop": 1,
    "clan-castle": 1,
    "bomb": 7,
    "spring-trap": 9,
    "air-bomb": 7,
    "giant-bomb": 7,
    "seeking-air-mine": 7,
    "skeleton-trap": 3,
    "tornado-trap": 1,
    "wall": 300,
  },
  14: {
    "town-hall": 1,
    "cannon": 7,
    "archer-tower": 8,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 5,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 3,
    "eagle-artillery": 1,
    "scattershot": 2,
    "builder-hut": 5,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "royal-champion": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "workshop": 1,
    "pet-house": 1,
    "clan-castle": 1,
    "bomb": 8,
    "spring-trap": 9,
    "air-bomb": 8,
    "giant-bomb": 7,
    "seeking-air-mine": 8,
    "skeleton-trap": 4,
    "tornado-trap": 1,
    "wall": 325,
  },
  15: {
    "town-hall": 1,
    "cannon": 7,
    "archer-tower": 8,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 5,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 3,
    "eagle-artillery": 1,
    "scattershot": 2,
    "builder-hut": 5,
    "monolith": 1,
    "spell-tower": 2,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "royal-champion": 1,
    "dragon-duke": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "workshop": 1,
    "pet-house": 1,
    "clan-castle": 1,
    "bomb": 9,
    "spring-trap": 9,
    "air-bomb": 9,
    "giant-bomb": 8,
    "seeking-air-mine": 9,
    "skeleton-trap": 4,
    "tornado-trap": 1,
    "wall": 325,
  },
  16: {
    "town-hall": 1,
    "cannon": 5,
    "archer-tower": 6,
    "multi-archer-tower": 2,
    "ricochet-cannon": 2,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 5,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 3,
    "eagle-artillery": 1,
    "scattershot": 2,
    "builder-hut": 5,
    "monolith": 1,
    "spell-tower": 2,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "royal-champion": 1,
    "dragon-duke": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "workshop": 1,
    "pet-house": 1,
    "clan-castle": 1,
    "bomb": 9,
    "spring-trap": 9,
    "air-bomb": 9,
    "giant-bomb": 8,
    "seeking-air-mine": 9,
    "skeleton-trap": 4,
    "tornado-trap": 1,
    "wall": 325,
  },
  17: {
    "town-hall": 1,
    "cannon": 5,
    "archer-tower": 6,
    "multi-archer-tower": 2,
    "ricochet-cannon": 2,
    "firespitter": 2,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 5,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 3,
    "eagle-artillery": 1,
    "scattershot": 2,
    "builder-hut": 5,
    "monolith": 1,
    "spell-tower": 2,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "royal-champion": 1,
    "dragon-duke": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "workshop": 1,
    "pet-house": 1,
    "clan-castle": 1,
    "bomb": 10,
    "spring-trap": 9,
    "air-bomb": 10,
    "giant-bomb": 8,
    "seeking-air-mine": 10,
    "skeleton-trap": 4,
    "tornado-trap": 1,
    "giga-bomb": 1,
    "wall": 325,
  },
  18: {
    "town-hall": 1,
    "cannon": 5,
    "archer-tower": 6,
    "multi-archer-tower": 2,
    "ricochet-cannon": 2,
    "firespitter": 2,
    "mortar": 4,
    "air-defense": 4,
    "wizard-tower": 5,
    "air-sweeper": 2,
    "hidden-tesla": 5,
    "bomb-tower": 2,
    "xbow": 4,
    "inferno-tower": 3,
    "eagle-artillery": 1,
    "scattershot": 2,
    "builder-hut": 5,
    "monolith": 1,
    "spell-tower": 2,
    "barbarian-king": 1,
    "archer-queen": 1,
    "minion-prince": 1,
    "grand-warden": 1,
    "royal-champion": 1,
    "dragon-duke": 1,
    "gold-mine": 7,
    "elixir-collector": 7,
    "dark-elixir-drill": 3,
    "gold-storage": 4,
    "elixir-storage": 4,
    "dark-elixir-storage": 1,
    "army-camp": 4,
    "barracks": 1,
    "dark-barracks": 1,
    "laboratory": 1,
    "spell-factory": 1,
    "dark-spell-factory": 1,
    "blacksmith": 1,
    "workshop": 1,
    "pet-house": 1,
    "clan-castle": 1,
    "bomb": 10,
    "spring-trap": 9,
    "air-bomb": 10,
    "giant-bomb": 8,
    "seeking-air-mine": 10,
    "skeleton-trap": 4,
    "tornado-trap": 1,
    "giga-bomb": 1,
    "wall": 325,
  },
};

export function getBuildingLimit(thLevel: number, buildingId: string): number {
  const safeTh = Math.max(1, Math.min(18, Math.trunc(thLevel) || 1));
  const limits = TH_BUILDING_LIMITS[safeTh] || TH_BUILDING_LIMITS[1];
  return limits[buildingId] || 0;
}

export function getAllBuildingLimits(thLevel: number): Record<string, number> {
  const safeTh = Math.max(1, Math.min(18, Math.trunc(thLevel) || 1));
  return TH_BUILDING_LIMITS[safeTh] || TH_BUILDING_LIMITS[1];
}

export interface ValidationResult {
  isValid: boolean;
  validBuildings: any[];
  invalidBuildings: any[];
  issues: string[];
}

export function validateLayoutAgainstLimits(buildings: any[], thLevel: number): ValidationResult {
  const limits = getAllBuildingLimits(thLevel);
  const currentCounts: Record<string, number> = {};
  const validBuildings: any[] = [];
  const invalidBuildings: any[] = [];
  const issues = new Set<string>();

  for (const b of buildings) {
    if (!b || !b.buildingId) continue;
    
    const limit = limits[b.buildingId] || 0;
    const currentCount = currentCounts[b.buildingId] || 0;

    if (limit === 0) {
      invalidBuildings.push(b);
      issues.add(`Công trình "${b.buildingId}" chưa được mở khóa ở TH${thLevel}.`);
    } else if (currentCount >= limit) {
      invalidBuildings.push(b);
      issues.add(`Công trình "${b.buildingId}" vượt quá giới hạn cho phép ở TH${thLevel} (Tối đa: ${limit}).`);
    } else {
      currentCounts[b.buildingId] = currentCount + 1;
      validBuildings.push(b);
    }
  }

  return {
    isValid: invalidBuildings.length === 0,
    validBuildings,
    invalidBuildings,
    issues: Array.from(issues)
  };
}
