import type { BuildingCategory, BuildingDef } from "./types";

export const GRID_SIZE = 44; // 44x44 tiles: the buildable home village grid (unchanged — saved layout coordinates stay valid)
export const CELL_SIZE_PX = 18; // Default pixel size per tile

// Real Clash of Clans home village is a 50x50 map: the 44x44 buildable grid
// plus a 3-tile-wide grass border on every side. Buildings can't be placed
// there, but decorations can, and — crucially — so can enemy troops, so a
// defense at the very edge of the buildable grid is NOT protected by the
// map edge the way a naive "is this the boundary of the array" check would
// assume. Building coordinates stay 0..GRID_SIZE; decoration/deployment
// coordinates additionally range over this border, i.e. -MAP_BORDER..GRID_SIZE+MAP_BORDER.
export const MAP_BORDER = 3;
export const MAP_TOTAL_SIZE = GRID_SIZE + MAP_BORDER * 2; // 50

export const CATEGORY_LABELS: Record<BuildingCategory, { label: string; icon: string }> = {
  defense: { label: "Phòng thủ", icon: "Shield" },
  resource: { label: "Tài nguyên", icon: "Coins" },
  army: { label: "Quân đội", icon: "Swords" },
  hero: { label: "Hero Altar", icon: "Crown" },
  trap: { label: "Bẫy", icon: "Bomb" },
  wall: { label: "Tường thành", icon: "Layers" },
};

export const BUILDINGS_CATALOG: BuildingDef[] = [
  // --- Town Hall & Core ---
  {
    id: "town-hall",
    name: "Town Hall",
    category: "defense",
    width: 4,
    height: 4,
    range: 10,
    minRange: 0,
    color: "#ffc857",
    accentColor: "#e6a119",
    weaponType: "both",
    description: "Nhà chính - Trọng tâm phòng thủ của làng (Giga Tesla/Inferno từ TH12+)",
  },

  // --- Defenses ---
  {
    id: "cannon",
    name: "Cannon",
    category: "defense",
    width: 3,
    height: 3,
    range: 9,
    color: "#e67e22",
    weaponType: "ground",
    description: "Pháo tầm gần - bắn đơn mục tiêu trên bộ",
  },
  {
    id: "archer-tower",
    name: "Archer Tower",
    category: "defense",
    width: 3,
    height: 3,
    range: 10,
    color: "#3498db",
    weaponType: "both",
    description: "Tháp cung thủ - bắn cả bộ lẫn bay tầm xa",
  },
  {
    id: "mortar",
    name: "Mortar",
    category: "defense",
    width: 3,
    height: 3,
    range: 11,
    minRange: 4,
    color: "#95a5a6",
    weaponType: "ground",
    description: "Pháo cối ném đạn diện rộng, có điểm mù 4 ô xung quanh",
  },
  {
    id: "air-defense",
    name: "Air Defense",
    category: "defense",
    width: 3,
    height: 3,
    range: 10,
    color: "#e74c3c",
    weaponType: "air",
    description: "Pháo phòng không uy lực cao chuyên bắn mục tiêu bay",
  },
  {
    id: "wizard-tower",
    name: "Wizard Tower",
    category: "defense",
    width: 3,
    height: 3,
    range: 7,
    color: "#9b59b6",
    weaponType: "both",
    description: "Tháp phù thủy gây sát thương phép diện rộng",
  },
  {
    id: "air-sweeper",
    name: "Air Sweeper",
    category: "defense",
    width: 2,
    height: 2,
    range: 15,
    minRange: 1,
    color: "#1abc9c",
    weaponType: "air",
    description: "Máy thổi gió đẩy lùi mục tiêu bay",
  },
  {
    id: "hidden-tesla",
    name: "Hidden Tesla",
    category: "defense",
    width: 2,
    height: 2,
    range: 7,
    color: "#f1c40f",
    weaponType: "both",
    description: "Trụ sét ẩn bất ngờ xuất hiện tấn công",
  },
  {
    id: "bomb-tower",
    name: "Bomb Tower",
    category: "defense",
    width: 3,
    height: 3,
    range: 6,
    color: "#d35400",
    weaponType: "ground",
    description: "Tháp ném bom diện rộng sát thương bộ, nổ bom tử vì đạo khi sập",
  },
  {
    id: "xbow",
    name: "X-Bow",
    category: "defense",
    width: 3,
    height: 3,
    range: 14,
    color: "#8e44ad",
    weaponType: "both",
    description: "Nỏ thần tốc độ bắn cực nhanh (bộ hoặc bộ & bay)",
  },
  {
    id: "inferno-tower",
    name: "Inferno Tower",
    category: "defense",
    width: 3,
    height: 3,
    range: 10,
    color: "#c0392b",
    weaponType: "both",
    description: "Tháp dung nham đốt đơn mục tiêu tăng dần hoặc đa mục tiêu",
  },
  {
    id: "eagle-artillery",
    name: "Eagle Artillery",
    category: "defense",
    width: 4,
    height: 4,
    range: 50,
    minRange: 7,
    color: "#f39c12",
    weaponType: "both",
    description: "Pháo đại bàng kích hoạt khi địch thả nhiều quân, bắn toàn map",
  },
  {
    id: "scattershot",
    name: "Scattershot",
    category: "defense",
    width: 3,
    height: 3,
    range: 10,
    minRange: 3,
    color: "#16a085",
    weaponType: "both",
    description: "Máy bắn đá tán xạ nổ đạn hình nón về phía sau mục tiêu",
  },
  {
    id: "builder-hut",
    name: "Builder's Hut",
    category: "defense",
    width: 2,
    height: 2,
    range: 7,
    color: "#7f8c8d",
    weaponType: "both",
    description: "Nhà thợ xây (có trang bị vũ khí và tự sửa chữa công trình ở TH14+)",
  },
  {
    id: "monolith",
    name: "Monolith",
    category: "defense",
    width: 3,
    height: 3,
    range: 11,
    color: "#2c3e50",
    accentColor: "#9b59b6",
    weaponType: "both",
    description: "Trụ đá hắc ám bắn phần trăm máu tối đa cực mạnh",
  },
  {
    id: "spell-tower",
    name: "Spell Tower",
    category: "defense",
    width: 2,
    height: 2,
    range: 4.5,
    color: "#8e44ad",
    weaponType: "both",
    description: "Tháp phép kích hoạt bùa Tàng hình, Độc hoặc Cuồng nộ",
  },
  {
    id: "multi-archer-tower",
    name: "Multi-Archer Tower",
    category: "defense",
    width: 3,
    height: 3,
    range: 10,
    color: "#2980b9",
    weaponType: "both",
    description: "Tháp đa cung thủ ghép từ 2 Archer Tower",
  },
  {
    id: "ricochet-cannon",
    name: "Ricochet Cannon",
    category: "defense",
    width: 3,
    height: 3,
    range: 9,
    color: "#d35400",
    weaponType: "ground",
    description: "Pháo đạn nảy ghép từ 2 Cannon, nảy sang mục tiêu thứ 2",
  },
  {
    id: "firespitter",
    name: "Firespitter",
    category: "defense",
    width: 3,
    height: 3,
    range: 10,
    color: "#e74c3c",
    weaponType: "both",
    description: "Phòng thủ phun lửa định hướng ở TH17",
  },

  // --- Resources ---
  {
    id: "gold-mine",
    name: "Gold Mine",
    category: "resource",
    width: 3,
    height: 3,
    color: "#ffd32a",
    description: "Mỏ khai thác vàng",
  },
  {
    id: "elixir-collector",
    name: "Elixir Collector",
    category: "resource",
    width: 3,
    height: 3,
    color: "#ff5e57",
    description: "Hút Elixir tím từ lòng đất",
  },
  {
    id: "dark-elixir-drill",
    name: "Dark Elixir Drill",
    category: "resource",
    width: 3,
    height: 3,
    color: "#575fcf",
    description: "Khoan hút Dark Elixir đen quý hiếm",
  },
  {
    id: "gold-storage",
    name: "Gold Storage",
    category: "resource",
    width: 3,
    height: 3,
    color: "#ffa801",
    description: "Kho chứa vàng lượng máu cao",
  },
  {
    id: "elixir-storage",
    name: "Elixir Storage",
    category: "resource",
    width: 3,
    height: 3,
    color: "#ef5777",
    description: "Kho chứa Elixir tím lượng máu cao",
  },
  {
    id: "dark-elixir-storage",
    name: "Dark Elixir Storage",
    category: "resource",
    width: 3,
    height: 3,
    color: "#3c40c6",
    description: "Kho chứa Dark Elixir quan trọng nhất",
  },

  // --- Army Buildings ---
  {
    id: "clan-castle",
    name: "Clan Castle",
    category: "army",
    width: 3,
    height: 3,
    range: 12,
    color: "#0be881",
    weaponType: "both",
    description: "Lâu đài Clan chứa quân thủ và lính viện trợ",
  },
  {
    id: "army-camp",
    name: "Army Camp",
    category: "army",
    width: 4,
    height: 4,
    color: "#05c46b",
    description: "Trại lính tập kết quân đội (kích thước 4x4)",
  },
  {
    id: "barracks",
    name: "Barracks",
    category: "army",
    width: 3,
    height: 3,
    color: "#4bcffa",
    description: "Nhà lính huấn luyện quân thường",
  },
  {
    id: "dark-barracks",
    name: "Dark Barracks",
    category: "army",
    width: 3,
    height: 3,
    color: "#0fbcf9",
    description: "Nhà lính Dark huấn luyện quân tinh nhuệ",
  },
  {
    id: "laboratory",
    name: "Laboratory",
    category: "army",
    width: 3,
    height: 3,
    color: "#d2dae2",
    description: "Phòng thí nghiệm nghiên cứu nâng cấp quân & phép",
  },
  {
    id: "spell-factory",
    name: "Spell Factory",
    category: "army",
    width: 3,
    height: 3,
    color: "#485460",
    description: "Nhà máy điều chế bình phép thuật Elixir",
  },
  {
    id: "dark-spell-factory",
    name: "Dark Spell Factory",
    category: "army",
    width: 3,
    height: 3,
    color: "#1e272e",
    description: "Nhà máy điều chế phép Dark Elixir",
  },
  {
    id: "blacksmith",
    name: "Blacksmith",
    category: "army",
    width: 3,
    height: 3,
    color: "#ff3f34",
    description: "Lò rèn trang bị Hero Equipment",
  },
  {
    id: "workshop",
    name: "Workshop",
    category: "army",
    width: 3,
    height: 3,
    color: "#ffc048",
    description: "Xưởng chế tạo Siege Machine máy công thành",
  },
  {
    id: "pet-house",
    name: "Pet House",
    category: "army",
    width: 3,
    height: 3,
    color: "#00d8d6",
    description: "Nhà nuôi và huấn luyện Hero Pets",
  },
  {
    id: "hero-hall",
    name: "Hero Hall",
    category: "army",
    width: 4,
    height: 4,
    color: "#8e44ad",
    accentColor: "#f39c12",
    description: "Nhà tướng - Quản lý và nâng cấp tất cả các Hero của làng",
  },
  {
    id: "hero-banner",
    name: "Hero Banner",
    category: "hero",
    width: 2,
    height: 2,
    range: 9,
    color: "#e67e22",
    weaponType: "both",
    description: "Cờ tướng phòng thủ - Nơi Hero tuần tra bảo vệ làng",
  },
  {
    id: "helper-hut",
    name: "Helper Hut",
    category: "resource",
    width: 2,
    height: 2,
    color: "#16a085",
    accentColor: "#2ecc71",
    description: "Nhà phụ tá - Chứa thợ học việc và trợ lý nghiên cứu",
  },

  // --- Hero Altars (Legacy / Backward Compatibility) ---
  {
    id: "barbarian-king",
    name: "Barbarian King Altar",
    category: "hero",
    width: 3,
    height: 3,
    range: 9,
    color: "#e67e22",
    weaponType: "ground",
    description: "Bệ đứng Vua Man Di",
  },
  {
    id: "archer-queen",
    name: "Archer Queen Altar",
    category: "hero",
    width: 3,
    height: 3,
    range: 9,
    color: "#9b59b6",
    weaponType: "both",
    description: "Bệ đứng Nữ Hoàng Cung Thủ",
  },
  {
    id: "minion-prince",
    name: "Minion Prince Altar",
    category: "hero",
    width: 3,
    height: 3,
    range: 9,
    color: "#34495e",
    weaponType: "both",
    description: "Bệ đứng Hoàng Tử Minion",
  },
  {
    id: "grand-warden",
    name: "Grand Warden Altar",
    category: "hero",
    width: 3,
    height: 3,
    range: 10,
    color: "#3498db",
    weaponType: "both",
    description: "Bệ đứng Đại Quản Giáo (hào quang buff)",
  },
  {
    id: "royal-champion",
    name: "Royal Champion Altar",
    category: "hero",
    width: 3,
    height: 3,
    range: 9,
    color: "#1abc9c",
    weaponType: "both",
    description: "Bệ đứng Nữ Tướng Hoàng Gia",
  },
  {
    id: "dragon-duke",
    name: "Dragon Duke Altar",
    category: "hero",
    width: 3,
    height: 3,
    range: 9,
    color: "#e74c3c",
    weaponType: "both",
    description: "Bệ đứng Công Tước Rồng",
  },

  // --- Traps ---
  {
    id: "bomb",
    name: "Bomb",
    category: "trap",
    width: 1,
    height: 1,
    range: 1.5,
    color: "#7f8c8d",
    weaponType: "trap",
    description: "Bẫy nổ nhỏ gây sát thương bộ",
  },
  {
    id: "spring-trap",
    name: "Spring Trap",
    category: "trap",
    width: 1,
    height: 1,
    range: 0.7,
    color: "#95a5a6",
    weaponType: "trap",
    description: "Bẫy bật lò xo hất văng lính bộ",
  },
  {
    id: "air-bomb",
    name: "Air Bomb",
    category: "trap",
    width: 1,
    height: 1,
    range: 5,
    color: "#e74c3c",
    weaponType: "trap",
    description: "Bẫy nổ trên không diện rộng diệt bầy bay",
  },
  {
    id: "giant-bomb",
    name: "Giant Bomb",
    category: "trap",
    width: 2,
    height: 2,
    range: 2,
    color: "#c0392b",
    weaponType: "trap",
    description: "Bom khổng lồ gây sát thương bùng nổ cực lớn",
  },
  {
    id: "seeking-air-mine",
    name: "Seeking Air Mine",
    category: "trap",
    width: 1,
    height: 1,
    range: 4,
    color: "#2c3e50",
    weaponType: "trap",
    description: "Bình hắc ám tìm diệt rồng/healer đơn mục tiêu",
  },
  {
    id: "skeleton-trap",
    name: "Skeleton Trap",
    category: "trap",
    width: 1,
    height: 1,
    range: 5,
    color: "#bdc3c7",
    weaponType: "trap",
    description: "Bẫy xương triệu hồi lính xương làm phân tâm địch",
  },
  {
    id: "tornado-trap",
    name: "Tornado Trap",
    category: "trap",
    width: 1,
    height: 1,
    range: 3,
    color: "#16a085",
    weaponType: "trap",
    description: "Bẫy lốc xoáy cuốn hút và giam chân mọi đơn vị",
  },
  {
    id: "giga-bomb",
    name: "Giga Bomb",
    category: "trap",
    width: 2,
    height: 2,
    range: 2.5,
    color: "#8e44ad",
    weaponType: "trap",
    description: "Giga Bomb bẫy nổ quy mô lớn ở TH17+",
  },

  // --- Wall ---
  {
    id: "wall",
    name: "Tường thành",
    category: "wall",
    width: 1,
    height: 1,
    color: "#718093",
    accentColor: "#dcdde1",
    description: "Tường thành ngăn chặn hướng tiến của quân bộ",
  },
];

export const BUILDINGS_BY_ID = new Map<string, BuildingDef>(
  BUILDINGS_CATALOG.map((b) => [b.id, b])
);
